exports.up = async (sql) => {
  await sql`
	CREATE TABLE IF NOT EXISTS players (
		player_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		player_name varchar(50),
		e_mail varchar(50),
		nick_name varchar(50),
		pw_hash varchar(100)
	);`;

  await sql`
	CREATE TABLE IF NOT EXISTS sessions (
		session_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		token varchar(32),
		expiry_timestamp TIMESTAMP NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
		player_id integer NOT NULL REFERENCES players (player_id) ON DELETE CASCADE ON UPDATE CASCADE
	);`;
};

exports.down = async (sql) => {
  await sql`
	DROP TABLE IF EXISTS sessions;
	`;
  await sql`
	DROP TABLE IF EXISTS players;
	`;
};
